### ISSUE TITLE
sample有问题

### ISSUE THREAD

**Issue by treezhao1024** [Xavier-Lam/wechat-django#10]
custom_business 无法调用，数据库中有handler，但实际运行起来似乎没有读数据库并create_handler

**Comment by Xavier-Lam** [comment]
是主分支代码吗
之前因为调试,将installed_apps中的wechat注释掉,不小心提交上来了
https://github.com/Xavier-Lam/wechat-django/blob/0ea243067f5bc5e69cab6c4585d5e46d9399a583/sample/wechat/settings.py#L45
把注释打开看看

**Comment by treezhao1024** [comment]
初步成功，多谢哈，还要接着学习
