### ISSUE TITLE
normal reply 是否也可以采用类似custom reply的编程方式支持

### ISSUE THREAD

**Issue by treezhao1024** [Xavier-Lam/wechat-django#11]
采用custom reply，非认证公众号 Error code: 48001, message: api unauthorized hints。但腾讯只允许企业号认证，个人无法使用。

normal reply没有这个问题，但现在的实现过于死板，是否可以参考custom reply，将normal reply也实现为message handler的可编程形式？

**Comment by Xavier-Lam** [comment]
理论上两种处理方式应该是一样的,如果产生48001,是否是调用了主动回复(客服回复接口)
如果是的话,理由应该是在后台同一个message_handler配置reply时. 配置了多个回复,并且选择了回复全部的回复策略(默认),这时候其余回复会走主动回复接口

**Comment by treezhao1024** [comment]
了解了，多谢
