### ISSUE TITLE
menu的sync/publish有bug？message handler sync有同样问题

### ISSUE THREAD

**Issue by treezhao1024** [Xavier-Lam/wechat-django#12]
猜测是template解析的问题？以下是traceback的一部分：
template 'admin/wechat_django/menu/change_list.html'.
Traceback (most recent call last):
  File "/opt/env-wechat-django/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/opt/env-wechat-django/lib/python3.6/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'view_short_description'
结果是跳到这个地址，并出现403 Forbidden：
http://x.x.x.x:8000/admin/wechat_django/1/menu/**None**/objecttool/publish/

猜测是template解析问题，造成跳转地址混乱，强制采用admin/wechat_django/1/menu/objecttool/publish/ 看似能正常工作（测试私人账号，会报Error code: 48001，但sync没有问题）

**Comment by Xavier-Lam** [comment]
这个bug会在0.4.0修复,修改方法参见这里
https://github.com/Xavier-Lam/wechat-django/commit/798c190f2be8129ed8bd14b1d1058671cde74c76#diff-22c2ddf208e2038ecbaae93e536b20c4

**Comment by treezhao1024** [comment]
用0.4.0 OK

**Comment by Xavier-Lam** [comment]
@treezhao1024 建议暂时把wechat-django安装在项目根目录,0.4.0这边我改动量很大,还有很多代码没有合并进来,migrations 0006也会被修改.不要在生产环境中使用,等我全部完成发布新版本或合并主分支后再使用.
