### ISSUE TITLE
调用接口时候报错Error code: 10000, message: 没有API访问能力

### ISSUE THREAD

**Issue by XudongLiu** [Xavier-Lam/wechat-django#13]
想主动发消息，但是报错

Exception Type: | WeChatAbilityError
-- | --
Error code: 10000, message: 没有API访问能力

其他模块都应该可用
不知道这个是什么原因啊

**Comment by XudongLiu** [comment]
难道是没有获取token，但是其他公众号功能貌似没有问题啊

**Comment by Xavier-Lam** [comment]
一般没有填写该app的appsecret才会发生这种状况 没有填写appsecret 没办法获取token 亦无法调用其他微信接口

**Comment by XudongLiu** [comment]
![image](https://user-images.githubusercontent.com/1211835/72032828-89cec200-32cb-11ea-991e-b4c588f4c2cf.png)

但是我在微信号里面已经配置了

**Comment by Xavier-Lam** [comment]
get_by_name是在manager下,应该通过WeChatApp.objects.get_by_name调用 
如果确认appsecret已填,麻烦调试看下这个异常具体是哪里抛出的 给trace看下 我看这个只会在models.ability.Abilities.api这里才有 这里只判断了是否有appsecret

**Comment by XudongLiu** [comment]
已经发现并解决了问题，多谢您快速的解答。
