### ISSUE TITLE
在admin端，点击同步微信上的东西报错

### ISSUE THREAD

**Issue by ahaoao** [Xavier-Lam/wechat-django#14]
比如点击同步图文　跳转后显示　　您未获授权，无法查看此网页。
HTTP ERROR 403

**Comment by Xavier-Lam** [comment]
修复方式参见
https://github.com/Xavier-Lam/wechat-django/blob/798c190f2be8129ed8bd14b1d1058671cde74c76/wechat_django/sites/admin.py#L56

56-59行(包含)

0.4.0版本有修复 但是短期内没有发布计划 改动比较大 最近没有时间改
