### ISSUE TITLE
请问自动回复中的自定义业务下面的自定义程序这块怎么设置？

### ISSUE THREAD

**Issue by ArwenMax** [Xavier-Lam/wechat-django#15]
如题

**Comment by Xavier-Lam** [comment]
假设自定义程序是app/handlers.py下的handler1函数
则在handler1函数上加装`wechat_django.handler.message_handler`装饰器,在后台配置里添加app.handlers.handler1,函数接收`wechat_django.models.WeChatMessageInfo`对象,返回字符串或`wechatpy.replies.BaseReply`
参考 https://github.com/Xavier-Lam/wechat-django#自定义微信回复

**Comment by ArwenMax** [comment]
谢谢
