### ISSUE TITLE
搜索中template search_form.html的cl.app_id取不到值

### ISSUE THREAD

**Issue by ArwenMax** [Xavier-Lam/wechat-django#16]
搜索中template search_form.html的cl.app_id取不到值，导致搜索功能无法实现

**Comment by Xavier-Lam** [comment]
具体哪个admin的什么问题?看描述不是很明白

**Comment by ArwenMax** [comment]
所有的搜索功能都实现不了，因为cl.app_id貌似没有赋值成功

**Comment by Xavier-Lam** [comment]
烦请提供以下django版本,wechat-django版本以及python版本

**Comment by ArwenMax** [comment]
Python 3.8.5
Django 3.1.0
wechat-django 0.33(你的最新版本）

**Comment by Xavier-Lam** [comment]
问题已确认 应该是由django 3引起的 要看下怎么处理 如果急用可以暂时先退回django 2版本
