### ISSUE TITLE
我用rest framework 无法获得session

### ISSUE THREAD

**Issue by Wuliaodewo** [Xavier-Lam/wechat-django#18]
作者您好，我在使用你的包，但是我想前后端分离开发，我看到您说可以支持 rest framework, 但是前后端分离，session无法正常获得，数据库还有一个表是session。这个包是可以把session入库吗？请问改如何配置？

**Comment by Xavier-Lam** [comment]
抱歉回复迟了
看了一下 确实不是很方便 方案有2:
1. 在你的drf view基类复写_update_wechat_info方法,调用wechat = super()._update_wechat_info后,将自己记录的openid赋给 wechat._openid 然后return wechat
2. 自己写一个Authentication类,继承默认的WeChatOAuthAuthentication,在authenticate方法中,同样自行给wechat._openid赋值,对于拿code新授权的状况,走super().authenticate(),在你的view中采用你自己写的Authentication类
