### ISSUE TITLE
请问这个项目可以用于正式环境了吗？

### ISSUE THREAD

**Issue by ramwin** [Xavier-Lam/wechat-django#2]
有先例吗？整体代码看下来觉得很不错呢。只是看了README里面的说明，有点不放心啊。

**Comment by Xavier-Lam** [comment]
如果自己测试没有什么问题的话 可以使用的 我有项目在用 有问题可以提issue或者pull request 我会处理
但确实不排除之后发布的版本会有breaking change 最好定死安装的版本(目前0.3.0) 如果后面要更新版本 breaking change我会写在CHANGELOG.md里 注意阅读

**Comment by ramwin** [comment]
好的，谢谢。下次做项目用这个来做。
