### ISSUE TITLE
请问支持4.0以上版本了吗？

### ISSUE THREAD

**Issue by hogking** [Xavier-Lam/wechat-django#25]
请教一下，看了之前的ISSUES，似乎没有更新？感谢作者

**Comment by Xavier-Lam** [comment]
因为我这边目前没有使用这块的需求,这个项目我这边基本上不会做维护和更新了,如果有PR我会合

**Comment by JooPoo** [comment]
代码是支持4.0的，但pip包不支持。

> 请教一下，看了之前的ISSUES，似乎没有更新？感谢作者

**Comment by Xavier-Lam** [comment]
这个我有些忘了 看了下我pypi确实没更新 应该是由于那时候pr并进来以后 我发现单测没过 所以就没推pypi了
pr作者有说要补单测 后来没有回复了
因为我自己没有在django 3以上使用本包 这个只能你们自己在项目内测一下有什么问题了

**Comment by hogking** [comment]
好的谢谢各位
