### ISSUE TITLE
请问支付回调url和消息的回调url分别是什么？

### ISSUE THREAD

**Issue by ramwin** [Xavier-Lam/wechat-django#3]
我在文档里搜索好像只看到了配置message_handle，没搜索到支付订单回调以及消息回调的设置文档．

**Comment by Xavier-Lam** [comment]
1. 消息回调
消息回调框架自动处理,实际回调的地址就是后台微信号配置中的回调地址项,既`app.build_url("handler")`.
对于一般业务,消息回复在后台配置就好了,对于自定义业务,以message_handler装饰,再配置到后台.
如果需要所有接受消息都走一个信号处理一下,并且还继续走后台配置的消息处理的话,目前确实没有这个功能,之后会考虑添加.
如果所有消息都想要自己处理,在后台配置一个规则为ALL的处理器指向你自己的message_handler就可以了

2. 支付回调
支付回调框架会自动处理,回调地址`app.build_url("order_notify", kwargs=dict(payname=app.pay.name))`.
支付状态变更采用信号通知,订阅的信号为`wechat_django.pay.signals.order_updated`,使用方法参见[这里](https://github.com/Xavier-Lam/wechat-django/blob/master/README.md#统一下单).
这边文档有一个错误,sender实际上应该为app的wechat_django.utils.func.Static("{appname}.{payname}"),并非re.compile 如果监听时不设置sender可以忽略

**Comment by ramwin** [comment]
好的,谢谢.
