### ISSUE TITLE
支付的时候能够传入 django user_id 吗？

### ISSUE THREAD

**Issue by JoshYuJump** [Xavier-Lam/wechat-django#7]
只需要使用微信支付的时候，`wechat_django.models.WeChatUser` 这个模型是没有数据的
但是又需要在回调的时候，order 里面有 user_id 的信息。

**Comment by Xavier-Lam** [comment]
不是很明白这个问题...
一般来说,你应该用out_trade_no来关联你的订单,进一步取得你订单的用户,这个out_trade对应的应该是你的订单模型
或者,生成订单时把你的user_id放在attach字段里,回调的时候根据attach查询你的用户信息
`app.pay.create_order(..., attach="your-user-id")`

如果是不在本框架内生成的订单,或者付款码支付的回调,之前确实没有考虑这种情况,这种情况因为事先库里没有对应数据,回调会被直接拒绝

**Comment by JoshYuJump** [comment]
@Xavier-Lam 
谢谢，你的回复能够解决我的问题

**Comment by JoshYuJump** [comment]
使用 `attach` 没有保存成功，`wechat_django_pay_unifiedorder` 好像没有 `attach` 字段，最后使用的 `ext_info`

```python
order = app.pay.create_order(
    trade_type='APP',
    body="body", total_fee=1,
    out_trade_no=self.create_trade_no(request.user.id),
    ext_info={
        'user_id': request.user.id,
        'product_id': 'life',
    }
)
```

**Comment by Xavier-Lam** [comment]
抱歉,刚看了一下,是这样的,我这边确实没有attach字段,这个字段是.prepay的时候传入的,不做存储,只是回调的时候可以拿到
```python
order = app.pay.create_order(...)
prepay = order.prepay(attach="xxx")
````
