### ISSUE TITLE
需要更新jsonfiled里six的引用方式

### ISSUE THREAD

**Issue by vicvinc** [Xavier-Lam/wechat-django#9]
django > 3.0
django.utils.six - Remove usage of this vendored library or switch to six.

https://pypi.org/project/six/

需要更新jsonfiled里six的引用，建议维护jsonfield包下encoder
```python
from django.utils import timezone
```
更新为
```python
from django.utils import timezone
import six
```

**Comment by Xavier-Lam** [comment]
已经在下一个大版本中更新,本版本如果没有特殊bug修复暂时不更新了
依赖可以改装jsonfield2==3.0.3

**Comment by vicvinc** [comment]
django这个版本更的有点蛋疼，很多跟six依赖的现在都出错了

**Comment by vicvinc** [comment]
楼主关了这个issue吧，估计过几天所有的包都会更关于six引用的问题，也不是啥大问题
